# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 049b2ac50885737f87e0bae925df86f101dbd0c22f147c81dd603fbc9a2f4f7dbc4944eb31c799e3cbc00d570280bb897bbce7eb082b81883292b6cd67ccb125

test:
  secret_key_base: 9a8748e93014b63faa92f454be37ba083f663471552de83f5819775bf937f8d56bae036dfed5079f0c25601bbedc567e793d916da1df60c9c6d0c2bb47944c79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
